name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet on Issue
